import React, { createContext, useContext } from "react";
import { Text as NativeText } from "react-native";

const dictionaries = {
  Afrikaans: {
    Home: "Tuis",
    Hazard: "Gevaar",
    Handover: "Oorhandiging",
    Inspection: "Inspeksie",
    Alerts: "Waarskuwings",
    Settings: "Instellings",
    SETTINGS: "INSTELLINGS",
    "Profile": "Profiel",
    "Profile Picture": "Profielprent",
    "Site Supervisor": "Terreinopsigter",
    "Notifications": "Kennisgewings",
    "Hazard Alerts": "Gevaarwaarskuwings",
    "Shift Reminders": "Skofherinneringe",
    "Reminder Time": "Herinneringstyd",
    "Connectivity": "Konnektiwiteit",
    "Offline Mode": "Vanlynmodus",
    "Appearance": "Voorkoms",
    "Theme": "Tema",
    "Language": "Taal",
    "Security": "Sekuriteit",
    "Change Password": "Verander wagwoord",
    "Active Sessions": "Aktiewe sessies",
    "About": "Oor",
    "Release Notes": "Vrystellingsnotas",
    "Privacy Policy": "Privaatheidsbeleid",
    "App Version": "Programweergawe",
    "Sign Out": "Teken uit",
    "SELECT THEME": "KIES TEMA",
    "SELECT LANGUAGE": "KIES TAAL",
    "SHIFT REMINDER TIME": "SKOFHERINNERINGSTYD",
    "ACTIVE SITE": "AKTIEWE TERREIN",
    "ACTIVE SHIFT": "AKTIEWE SKOF",
    "CREW ON SHIFT": "SPAN OP SKOF",
    "ACTIVE HAZARDS": "AKTIEWE GEVARE",
    "Daily Inspection Report": "Daaglikse inspeksieverslag",
    "View Inspection Reports": "Bekyk inspeksieverslae",
    "ACKNOWLEDGE": "ERKEN",
    "VIEW FULL REPORT": "BEKYK VOLLEDIGE VERSLAG",
    "DELETE HAZARD & IMAGE": "SKRAP GEVAAR EN FOTO",
    "Delete hazard": "Skrap gevaar",
    "Cancel": "Kanselleer",
    "Delete": "Skrap",
    "Hazard not deleted": "Gevaar nie geskrap nie",
    "sorry consult supervisor": "jammer, raadpleeg opsigter",
    "RAISE HAZARD ALERT": "STUUR GEVAARWAARSKUWING",
    "Hazard Type *": "Gevaartipe *",
    "Zone *": "Sone *",
    "Description *": "Beskrywing *",
    "Photo Evidence": "Fotobewys",
    "optional": "opsioneel",
    "CAPTURE": "NEEM FOTO",
    "GALLERY": "GALERY",
    "NEXT - SET SEVERITY": "VOLGENDE - STEL ERNS",
    "SET SEVERITY LEVEL": "STEL ERNSVLAK",
    "REVIEW & BROADCAST": "HERSIEN EN STUUR",
    "REVIEW & CONFIRM": "HERSIEN EN BEVESTIG",
    "BROADCAST ALERT NOW": "STUUR WAARSKUWING NOU",
    "BACK TO EDIT": "TERUG NA WYSIG",
    "CREATE HANDOVER": "SKEP OORHANDIGING",
    "Create Handover": "Skep oorhandiging",
    "Review Handover": "Hersien oorhandiging",
    "Supervisor Shift Controls": "Opsigter skofkontroles",
    "Supervisor Review Controls": "Opsigter hersienkontroles",
    "Team Assignment": "Spantoewysing",
    "Notifications": "Kennisgewings",
    "Incoming team": "Inkomende span",
    "Outgoing team": "Uitgaande span",
    "Supervisors": "Opsigters",
    "Day Shift": "Dagskof",
    "Night Shift": "Nagskof",
    "Day / Night Shift": "Dag- / nagskof",
    "Task Allocation": "Taaktoewysing",
    "SAVE SUPERVISOR CHANGES": "STOOR OPSIGTERWYSIGINGS",
    "Handover updated": "Oorhandiging opgedateer",
    "Supervisor changes to shift, task allocation, and notifications have been applied.": "Opsigterwysigings aan skof, taaktoewysing en kennisgewings is toegepas.",
    "Supervisor can update shift, tasks, and notifications": "Opsigter kan skof, take en kennisgewings verander",
    "Only supervisors can change shift type, task allocation, and who receives handover notifications.": "Slegs opsigters kan skoftipe, taaktoewysing en kennisgewingontvangers verander.",
    "Outgoing Team": "Uitgaande span",
    "Incoming Team": "Inkomende span",
    "Hazards Carried Over": "Gevare oorgedra",
    "Tasks For Incoming Team": "Take vir inkomende span",
    "HANDOVER REVIEW": "OORHANDIGINGHERSIENING",
    "ACKNOWLEDGE & BRIEF TEAM": "ERKEN EN LIG SPAN IN",
    "FLAG ISSUE TO OUTGOING SUPERVISOR": "MERK KWESSIE VIR UITGAANDE OPSIGTER",
    "NEW INSPECTION": "NUWE INSPEKSIE",
    "INSPECTION REPORTS": "INSPEKSIEVERSLAE",
    "NOTIFICATIONS": "KENNISGEWINGS",
    "No live notifications": "Geen lewendige kennisgewings nie",
    "SIGN IN": "TEKEN IN",
    "EMAIL": "E-POS",
    "PASSWORD": "WAGWOORD",
    "CREATE ACCOUNT": "SKEP REKENING",
    "RESET PASSWORD": "HERSTEL WAGWOORD",
    "SEND RESET LINK": "STUUR HERSTELSKAKEL",
    "back to sign in": "terug na inteken",
    "forgot password?": "wagwoord vergeet?",
  },
  German: {
    Home: "Start",
    Hazard: "Gefahr",
    Handover: "Ubergabe",
    Inspection: "Prufung",
    Alerts: "Alarme",
    Settings: "Einstellungen",
    SETTINGS: "EINSTELLUNGEN",
    Profile: "Profil",
    "Profile Picture": "Profilbild",
    "Site Supervisor": "Standortleiter",
    Notifications: "Benachrichtigungen",
    "Hazard Alerts": "Gefahrenalarme",
    "Shift Reminders": "Schichterinnerungen",
    "Reminder Time": "Erinnerungszeit",
    Connectivity: "Verbindung",
    "Offline Mode": "Offline-Modus",
    Appearance: "Darstellung",
    Theme: "Design",
    Language: "Sprache",
    Security: "Sicherheit",
    "Change Password": "Passwort andern",
    "Active Sessions": "Aktive Sitzungen",
    About: "Info",
    "Release Notes": "Versionshinweise",
    "Privacy Policy": "Datenschutz",
    "App Version": "App-Version",
    "Sign Out": "Abmelden",
    "SELECT THEME": "DESIGN AUSWAHLEN",
    "SELECT LANGUAGE": "SPRACHE AUSWAHLEN",
    "ACTIVE SITE": "AKTIVER STANDORT",
    "ACTIVE SHIFT": "AKTIVE SCHICHT",
    "CREW ON SHIFT": "TEAM IN SCHICHT",
    "ACTIVE HAZARDS": "AKTIVE GEFAHREN",
    "Daily Inspection Report": "Taglicher Prufbericht",
    "View Inspection Reports": "Prufberichte ansehen",
    ACKNOWLEDGE: "BESTATIGEN",
    "VIEW FULL REPORT": "VOLLEN BERICHT ANSEHEN",
    "DELETE HAZARD & IMAGE": "GEFAHR UND BILD LOSCHEN",
    "Delete hazard": "Gefahr loschen",
    Cancel: "Abbrechen",
    Delete: "Loschen",
    "Hazard not deleted": "Gefahr nicht geloscht",
    "sorry consult supervisor": "bitte Supervisor konsultieren",
    "RAISE HAZARD ALERT": "GEFAHRENALARM ERSTELLEN",
    "Hazard Type *": "Gefahrentyp *",
    "Zone *": "Zone *",
    "Description *": "Beschreibung *",
    "Photo Evidence": "Fotonachweis",
    optional: "optional",
    CAPTURE: "AUFNEHMEN",
    GALLERY: "GALERIE",
    "NEXT - SET SEVERITY": "WEITER - SCHWEREGRAD SETZEN",
    "SET SEVERITY LEVEL": "SCHWEREGRAD SETZEN",
    "REVIEW & BROADCAST": "PRUFEN UND SENDEN",
    "REVIEW & CONFIRM": "PRUFEN UND BESTATIGEN",
    "BROADCAST ALERT NOW": "ALARM JETZT SENDEN",
    "BACK TO EDIT": "ZURUCK ZUM BEARBEITEN",
    "CREATE HANDOVER": "UBERGABE ERSTELLEN",
    "Create Handover": "Ubergabe erstellen",
    "Review Handover": "Ubergabe prufen",
    "Supervisor Shift Controls": "Supervisor-Schichtsteuerung",
    "Supervisor Review Controls": "Supervisor-Prufsteuerung",
    "Team Assignment": "Teamzuweisung",
    Notifications: "Benachrichtigungen",
    "Incoming team": "Kommendes Team",
    "Outgoing team": "Abgehendes Team",
    Supervisors: "Supervisoren",
    "Day Shift": "Tagschicht",
    "Night Shift": "Nachtschicht",
    "Day / Night Shift": "Tag- / Nachtschicht",
    "Task Allocation": "Aufgabenzuweisung",
    "SAVE SUPERVISOR CHANGES": "SUPERVISOR-ANDERUNGEN SPEICHERN",
    "Handover updated": "Ubergabe aktualisiert",
    "Supervisor changes to shift, task allocation, and notifications have been applied.": "Supervisor-Anderungen an Schicht, Aufgaben und Benachrichtigungen wurden angewendet.",
    "Supervisor can update shift, tasks, and notifications": "Supervisor kann Schicht, Aufgaben und Benachrichtigungen andern",
    "Only supervisors can change shift type, task allocation, and who receives handover notifications.": "Nur Supervisoren konnen Schichttyp, Aufgabenzuweisung und Empfanger andern.",
    "Outgoing Team": "Abgehendes Team",
    "Incoming Team": "Kommendes Team",
    "Hazards Carried Over": "Ubertragene Gefahren",
    "Tasks For Incoming Team": "Aufgaben fur kommendes Team",
    "HANDOVER REVIEW": "UBERGABEPRUFUNG",
    "ACKNOWLEDGE & BRIEF TEAM": "BESTATIGEN UND TEAM EINWEISEN",
    "FLAG ISSUE TO OUTGOING SUPERVISOR": "PROBLEM AN ABGEHENDEN SUPERVISOR MELDEN",
    "NEW INSPECTION": "NEUE PRUFUNG",
    "INSPECTION REPORTS": "PRUFBERICHTE",
    NOTIFICATIONS: "BENACHRICHTIGUNGEN",
    "No live notifications": "Keine Live-Benachrichtigungen",
    "SIGN IN": "ANMELDEN",
    EMAIL: "E-MAIL",
    PASSWORD: "PASSWORT",
    "CREATE ACCOUNT": "KONTO ERSTELLEN",
    "RESET PASSWORD": "PASSWORT ZURUCKSETZEN",
    "SEND RESET LINK": "RESET-LINK SENDEN",
    "back to sign in": "zuruck zur Anmeldung",
    "forgot password?": "Passwort vergessen?",
  },
  Portuguese: {
    Home: "Inicio",
    Hazard: "Risco",
    Handover: "Turno",
    Inspection: "Inspecao",
    Alerts: "Alertas",
    Settings: "Definicoes",
    SETTINGS: "DEFINICOES",
    Profile: "Perfil",
    "Profile Picture": "Foto de perfil",
    "Site Supervisor": "Supervisor do local",
    Notifications: "Notificacoes",
    "Hazard Alerts": "Alertas de risco",
    "Shift Reminders": "Lembretes de turno",
    "Reminder Time": "Hora do lembrete",
    Connectivity: "Conectividade",
    "Offline Mode": "Modo offline",
    Appearance: "Aparencia",
    Theme: "Tema",
    Language: "Idioma",
    Security: "Seguranca",
    "Change Password": "Alterar palavra-passe",
    "Active Sessions": "Sessoes ativas",
    About: "Sobre",
    "Release Notes": "Notas da versao",
    "Privacy Policy": "Politica de privacidade",
    "App Version": "Versao da app",
    "Sign Out": "Terminar sessao",
    "SELECT THEME": "SELECIONAR TEMA",
    "SELECT LANGUAGE": "SELECIONAR IDIOMA",
    "ACTIVE SITE": "LOCAL ATIVO",
    "ACTIVE SHIFT": "TURNO ATIVO",
    "CREW ON SHIFT": "EQUIPA NO TURNO",
    "ACTIVE HAZARDS": "RISCOS ATIVOS",
    "Daily Inspection Report": "Relatorio diario de inspecao",
    "View Inspection Reports": "Ver relatorios de inspecao",
    ACKNOWLEDGE: "CONFIRMAR",
    "VIEW FULL REPORT": "VER RELATORIO COMPLETO",
    "DELETE HAZARD & IMAGE": "APAGAR RISCO E IMAGEM",
    "Delete hazard": "Apagar risco",
    Cancel: "Cancelar",
    Delete: "Apagar",
    "Hazard not deleted": "Risco nao apagado",
    "sorry consult supervisor": "desculpe, consulte o supervisor",
    "RAISE HAZARD ALERT": "CRIAR ALERTA DE RISCO",
    "Hazard Type *": "Tipo de risco *",
    "Zone *": "Zona *",
    "Description *": "Descricao *",
    "Photo Evidence": "Evidencia fotografica",
    optional: "opcional",
    CAPTURE: "CAPTURAR",
    GALLERY: "GALERIA",
    "NEXT - SET SEVERITY": "SEGUINTE - DEFINIR GRAVIDADE",
    "SET SEVERITY LEVEL": "DEFINIR GRAVIDADE",
    "REVIEW & BROADCAST": "REVER E ENVIAR",
    "REVIEW & CONFIRM": "REVER E CONFIRMAR",
    "BROADCAST ALERT NOW": "ENVIAR ALERTA AGORA",
    "BACK TO EDIT": "VOLTAR A EDITAR",
    "CREATE HANDOVER": "CRIAR PASSAGEM",
    "Create Handover": "Criar passagem",
    "Review Handover": "Rever passagem",
    "Supervisor Shift Controls": "Controlos de turno do supervisor",
    "Supervisor Review Controls": "Controlos de revisao do supervisor",
    "Team Assignment": "Atribuicao de equipa",
    Notifications: "Notificacoes",
    "Incoming team": "Equipa de entrada",
    "Outgoing team": "Equipa de saida",
    Supervisors: "Supervisores",
    "Day Shift": "Turno diurno",
    "Night Shift": "Turno noturno",
    "Day / Night Shift": "Turno diurno / noturno",
    "Task Allocation": "Atribuicao de tarefas",
    "SAVE SUPERVISOR CHANGES": "GUARDAR ALTERACOES DO SUPERVISOR",
    "Handover updated": "Passagem atualizada",
    "Supervisor changes to shift, task allocation, and notifications have been applied.": "As alteracoes do supervisor ao turno, tarefas e notificacoes foram aplicadas.",
    "Supervisor can update shift, tasks, and notifications": "O supervisor pode alterar turno, tarefas e notificacoes",
    "Only supervisors can change shift type, task allocation, and who receives handover notifications.": "Apenas supervisores podem alterar o tipo de turno, tarefas e notificacoes.",
    "Outgoing Team": "Equipa de saida",
    "Incoming Team": "Equipa de entrada",
    "Hazards Carried Over": "Riscos transferidos",
    "Tasks For Incoming Team": "Tarefas da equipa de entrada",
    "HANDOVER REVIEW": "REVISAO DA PASSAGEM",
    "ACKNOWLEDGE & BRIEF TEAM": "CONFIRMAR E INFORMAR EQUIPA",
    "FLAG ISSUE TO OUTGOING SUPERVISOR": "SINALIZAR AO SUPERVISOR DE SAIDA",
    "NEW INSPECTION": "NOVA INSPECAO",
    "INSPECTION REPORTS": "RELATORIOS DE INSPECAO",
    NOTIFICATIONS: "NOTIFICACOES",
    "No live notifications": "Sem notificacoes ao vivo",
    "SIGN IN": "ENTRAR",
    EMAIL: "EMAIL",
    PASSWORD: "PALAVRA-PASSE",
    "CREATE ACCOUNT": "CRIAR CONTA",
    "RESET PASSWORD": "REDEFINIR PALAVRA-PASSE",
    "SEND RESET LINK": "ENVIAR LINK",
    "back to sign in": "voltar ao login",
    "forgot password?": "esqueceu a palavra-passe?",
  },
  Oshiwambo: {
    Home: "Etameko",
    Hazard: "Oshiponga",
    Handover: "Oshilonga",
    Inspection: "Etaleko",
    Alerts: "Omalondodho",
    Settings: "Omalongekidho",
    SETTINGS: "OMALONGEKIDHO",
    Profile: "Profaila",
    "Profile Picture": "Ethano lya profaila",
    "Site Supervisor": "Omukuluntu gwoshilongo",
    Notifications: "Omalondodho",
    "Hazard Alerts": "Omalondodho gopshiponga",
    "Shift Reminders": "Oivululifo yoshift",
    "Reminder Time": "Efimbo lyokuvululifa",
    Connectivity: "Ekwatathano",
    "Offline Mode": "Omukalo gwopokati",
    Appearance: "Eholoko",
    Theme: "Tema",
    Language: "Elaka",
    Security: "Egameno",
    "Change Password": "Shintsha password",
    "Active Sessions": "Omasesho ga kwata",
    About: "Kombinga",
    "Release Notes": "Omapopyo goshikako",
    "Privacy Policy": "Ompango yomuule",
    "App Version": "Version yapp",
    "Sign Out": "Fuma mo",
    "SELECT THEME": "HOGOLA TEMA",
    "SELECT LANGUAGE": "HOGOLA ELAKA",
    "ACTIVE SITE": "OSHILONGO SHA KWATA",
    "ACTIVE SHIFT": "SHIFT YA KWATA",
    "CREW ON SHIFT": "OVAKWASHILONGA POSHIFT",
    "ACTIVE HAZARDS": "OIPONGA YA KWATA",
    "Daily Inspection Report": "Ripota yetaleko lyesiku",
    "View Inspection Reports": "Tala maripota getaleko",
    ACKNOWLEDGE: "ITAVELA",
    "VIEW FULL REPORT": "TALA RIPOTA AYIHE",
    "DELETE HAZARD & IMAGE": "DIMA OSHIPONGA NETHANO",
    "Delete hazard": "Dima oshiponga",
    Cancel: "Efa",
    Delete: "Dima",
    "Hazard not deleted": "Oshiponga inashi dimwa",
    "sorry consult supervisor": "ombili, pula omukuluntu",
    "RAISE HAZARD ALERT": "TUMA ELONDODHO LYOSHIPONGA",
    "Hazard Type *": "Omukalo gwoshiponga *",
    "Zone *": "Zone *",
    "Description *": "Efaneko *",
    "Photo Evidence": "Uumbangi wethano",
    optional: "ngaashi wa hala",
    CAPTURE: "KWATA ETHANO",
    GALLERY: "GALERI",
    "NEXT - SET SEVERITY": "TWALELE - TULA OMAKIPITO",
    "SET SEVERITY LEVEL": "TULA OMAKIPITO",
    "REVIEW & BROADCAST": "KONAKONA NOKUTUMA",
    "REVIEW & CONFIRM": "KONAKONA NOKUITAVELA",
    "BROADCAST ALERT NOW": "TUMA ELONDODHO PAIFE",
    "BACK TO EDIT": "GALUKA KOKULUNDULULA",
    "CREATE HANDOVER": "NONGA OMPITITHO",
    "Create Handover": "Nonga ompititho",
    "Review Handover": "Konakona ompititho",
    "Supervisor Shift Controls": "Omakontolola goshift gomukuluntu",
    "Supervisor Review Controls": "Omakontolola gekonakono gomukuluntu",
    "Team Assignment": "Etulopo lyekwata",
    Notifications: "Omalondodho",
    "Incoming team": "Ekwata lyokuya",
    "Outgoing team": "Ekwata lyokufuma",
    Supervisors: "Ovamakuluntu",
    "Day Shift": "Shift yoshikati",
    "Night Shift": "Shift youfiku",
    "Day / Night Shift": "Shift yoshikati / youfiku",
    "Task Allocation": "Etulopo lyoilonga",
    "SAVE SUPERVISOR CHANGES": "PONGA OMAPINGO GOMUKULUNTU",
    "Handover updated": "Ompititho ya lundululwa",
    "Supervisor changes to shift, task allocation, and notifications have been applied.": "Omapingo gomukuluntu koshift, oilonga nomalondodho ga tulwa mo.",
    "Supervisor can update shift, tasks, and notifications": "Omukuluntu ota dulu okulundulula shift, oilonga nomalondodho",
    "Only supervisors can change shift type, task allocation, and who receives handover notifications.": "Ovamakuluntu vike tava dulu okulundulula shift, oilonga naavo tava mono omalondodho.",
    "Outgoing Team": "Ekwata lyokufuma",
    "Incoming Team": "Ekwata lyokuya",
    "Hazards Carried Over": "Oiponga ya twalwa",
    "Tasks For Incoming Team": "Oilonga yekwata lyokuya",
    "HANDOVER REVIEW": "EKONAKONO LYOMPITITHO",
    "ACKNOWLEDGE & BRIEF TEAM": "ITAVELA NOKULOMBELA EKWATA",
    "FLAG ISSUE TO OUTGOING SUPERVISOR": "LOMBELA OMUKULUNTU GWOKUFUMA",
    "NEW INSPECTION": "ETALEKO EPE",
    "INSPECTION REPORTS": "MARIPOTA GETALEKO",
    NOTIFICATIONS: "OMALONDODHO",
    "No live notifications": "Kape na omalondodho",
    "SIGN IN": "INGILA",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
    "CREATE ACCOUNT": "NONGA ACCOUNT",
    "RESET PASSWORD": "TULULULA PASSWORD",
    "SEND RESET LINK": "TUMA LINK",
    "back to sign in": "galuka kokuingila",
    "forgot password?": "wa dhimbwa password?",
  },
};

const preserveCaseKeys = (dict) =>
  Object.fromEntries(Object.entries(dict).flatMap(([key, value]) => [[key, value], [key.toUpperCase(), String(value).toUpperCase()]]));

const withCaseVariants = Object.fromEntries(Object.entries(dictionaries).map(([language, dict]) => [language, preserveCaseKeys(dict)]));

const trimParts = (text) => {
  const leading = text.match(/^\s*/)?.[0] || "";
  const trailing = text.match(/\s*$/)?.[0] || "";
  return { leading, core: text.trim(), trailing };
};

export const translateText = (text, language) => {
  if (!text || language === "English") return text;
  const dict = withCaseVariants[language];
  if (!dict) return text;

  const { leading, core, trailing } = trimParts(text);
  if (!core) return text;
  if (dict[core]) return `${leading}${dict[core]}${trailing}`;

  let translated = core;
  for (const [source, target] of Object.entries(dict).sort((a, b) => b[0].length - a[0].length)) {
    if (source.length < 4) continue;
    translated = translated.split(source).join(target);
  }

  return `${leading}${translated}${trailing}`;
};

const translateChildren = (children, language) => {
  if (typeof children === "string") return translateText(children, language);
  if (Array.isArray(children)) return children.map((item) => translateChildren(item, language));
  return children;
};

const LocalizationContext = createContext({ language: "English" });

export function LocalizationProvider({ language = "English", children }) {
  return (
    <LocalizationContext.Provider value={{ language }}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useTranslate() {
  const { language } = useContext(LocalizationContext);
  return (text) => translateText(text, language);
}

export function LocalizedText({ children, ...props }) {
  const { language } = useContext(LocalizationContext);
  return <NativeText {...props}>{translateChildren(children, language)}</NativeText>;
}
